apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: portfolio_db
    user: portfolio_user
    secureJsonData:
      password: portfolio_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1500
